import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({subsets: ["latin"]})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
      
      <body >
        <Nav/>
        {children}
      
      </body>
    </html>
  );
}
